### ISSUE TITLE
for sale ?

### ISSUE THREAD

**Issue by poowu** [dang113108/591_rent#2]
請問那有支援中古屋嗎

**Comment by dang113108** [comment]
@poowu 你好，目前因為我自己還不需要的關係所以沒有支援。
但我相信基本上原理都是差不多的，撈 API 拿資料，所以如果你有需要的話可以 Fork 去修改。

總之，目前我沒有打算支援這個，非常抱歉。

**Comment by dang113108** [comment]
@poowu 你好，目前有其他高手做出中古屋的版本，您可以到PR那邊看看 : )
